import { Event } from './event';
import eventimg from '@/public/assets/event.jpg'
import image2g from '@/public/assets/img1.jpg'

export const events: Event[] = [

    {
      id: 1,
      name: 'Cosmos Mumbai led by Warden Protocol',
      date: '2024-07-28T14:00:00',
      time: '2:00 PM',
      venue: 'Lumos Cowork',
      organizer: 'Cosmoverse Dubai, Rhythm Jain & Warden',
      attendees: 241,
      imageUrl: eventimg,
      status: 'Completed',
      description: 'A blockchain-focused event on Cosmos technology in Mumbai.',
    },
    {
      id: 2,
      name: 'Polygon Community Call',
      date: '2024-09-30T21:30:00',
      time: '9:30 PM',
      venue: 'Virtual',
      organizer: 'Cale Moody',
      attendees: 545,
      imageUrl: eventimg,
      status: 'Invited',
    },
    {
      id: 3,
      name: 'DevFest 2024',
      date: '2024-10-05T10:00:00',
      time: '10:00 AM',
      venue: 'Google HQ',
      organizer: 'Google Developers',
      attendees: 1021,
      imageUrl: eventimg,
      status: 'Upcoming',
    },
    {
      id: 4,
      name: 'React Conference',
      date: '2024-10-15T09:00:00',
      time: '9:00 AM',
      venue: 'Virtual',
      organizer: 'React Community',
      attendees: 789,
      imageUrl: eventimg,
      status: 'Upcoming',
    },
    {
      id: 5,
      name: 'JS Conf 2023',
      date: '2023-09-15T09:00:00',
      time: '9:00 AM',
      venue: 'Virtual',
      organizer: 'JavaScript Enthusiasts',
      attendees: 890,
      imageUrl: eventimg,
      status: 'Completed',
    },
    {
      id: 6,
      name: 'Hackathon 2023',
      date: '2023-08-20T10:00:00',
      time: '10:00 AM',
      venue: 'Lumos Cowork',
      organizer: 'Tech Hackers',
      attendees: 620,
      imageUrl: eventimg,
      status: 'Completed',
    },
];